var StockViewConstants = {
    STOCK_VIEW_LOAD_STOCKS: 'STOCK_VIEW_LOAD_STOCKS',
    STCK_VIEW_GET_STOCK: 'STOCK_VIEW_GET_STOCK',
    STOCK_LIST_STOCK_ADDED: 'STOCK_LIST_FILTER_ADDED',
    STOCK_LIST_STOCK_DELETED: 'STOCK_LIST_STOCK_DELETED',
    STOCK_LIST_FILTERED: 'STOCK_LIST_FILTERED'
};

module.exports = StockViewConstants;
