var StockViewConstants = {
    STOCK_LIST_STOCK_ADDED: 'STOCK_LIST_FILTER_ADDED',
    STOCK_LIST_STOCK_DELETED: 'STOCK_LIST_STOCK_DELETED',
    STOCK_LIST_FILTERED: 'STOCK_LIST_FILTERED'
};

module.exports = StockViewConstants;
